init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd CleanInternetCaches
  - cmd: build.cmd AppVeyorBuildVersion
  - cmd: build.cmd All
  - cmd: build.cmd SourceLink
  - cmd: build.cmd NuGet
test: off
artifacts:
  - path: bin\*.nupkg
environment:
  FREEBASE_API_KEY: AIzaSyBTcOKmU7L7gFB4AdyAz75JRmdHixdLYjY
branches:
  except:
    - gh-pages
    - release
